[project]
name = "tutor-contrib-notifications"
description = "Tutor plugin that enables email notifications for Open edX"
authors = [
  { name = "Andres Gonzalez", email = "andres@aulasneo.com" },
]
license = { text = "AGPLv3" }
license-files = []
readme = { file = "README.rst", content-type = "text/x-rst" }
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU Affero General Public License v3",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "tutor>=20.0.0,<21.0.0",
]
dynamic = ["version"]

[project.urls]
Code = "https://github.com/aulasneo/tutor-contrib-notifications"
Issues = "https://github.com/aulasneo/tutor-contrib-notifications/issues"

[project.entry-points."tutor.plugin.v1"]
notifications = "tutornotifications.plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.custom]
path = ".hatch_build.py"

[tool.hatch.build.targets.wheel]
packages = ["tutornotifications"]

[tool.hatch.build.targets.sdist]
strict-naming = false
include = ["/tutornotifications", "/README.rst", "/LICENSE.txt", "/CHANGELOG.md", "/.hatch_build.py"]
exclude = ["tests*"]
